# Generated by Django 5.0.3 on 2024-03-27 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Serpientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cientifico', models.CharField(max_length=100)),
                ('nombre_comun', models.CharField(max_length=100)),
                ('habitat', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Caracteristica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venenosa', models.BooleanField(default=False)),
                ('color_patron', models.CharField(max_length=100)),
                ('alimentacion', models.CharField(max_length=100)),
                ('serpiente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Proyecto.serpientes')),
            ],
        ),
    ]
