# Generated by Django 5.0.2 on 2024-04-03 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto', '0002_formulario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caracteristica',
            name='serpiente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='Proyecto.serpientes'),
        ),
    ]
