# Generated by Django 5.0.2 on 2024-04-04 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto', '0003_alter_caracteristica_serpiente'),
    ]

    operations = [
        migrations.AddField(
            model_name='serpientes',
            name='foto',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
