# Generated by Django 5.0.2 on 2024-04-13 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto', '0007_remove_formulario_ubicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serpientes',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
